### ISSUE TITLE
Show the List of Sales and Marketing Reports

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1235]
**Is your feature request related to a problem? Please describe.**
On the reports page created in issue #1232, we need to show the list of the reports with type `sales-and-marketing`.

**Describe the solution you'd like**
**Part 1**
- [x] The list should be shown like the design provided below with the name of the report on the togglable bar.
- [x] The report list should be togglable. Just like the shown below
- [x] Every report should have a edit button in the bottom

**Reference images**

![image](https://user-images.githubusercontent.com/54376313/146639394-5a40e9d9-f9ce-4dd1-b078-f4932c0800fc.png)

![image](https://user-images.githubusercontent.com/54376313/146639546-9aa946f1-1167-444d-b938-8e17b9532749.png)

**Part 2**
- [x] The togglable bar containing the report name should also contain a view button that should redirect the user to a new page (mentioned in next point) where the report should be loaded.
- [x] We need to create a page where the report should be displayed. The page should contain
    - [x] Menubar
    - [x] Report Name
    - [x] Report Description
    - [x] An iframe tag in which the report will be loaded. An example is provided below  
          ```<iframe width="600" height="900" src="https://datastudio.google.com/embed/reporting/7d875374-261f-4f61-a9e5-4b632417d227/page/Js2hC" frameborder="0" style="border:0" allowfullscreen></iframe>```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dsajwan2020** [comment]
The feature for sales and marketing is implemented

Part 1

 The report list should be togglable.

![image](https://user-images.githubusercontent.com/96309135/162698124-f9cb8b08-83f4-48b4-b725-d5a34e2e1096.png)
 
Every report should have a edit button in the bottom

![image](https://user-images.githubusercontent.com/96309135/162698361-bc06ecff-94d9-4f65-a6bb-d7dbbed6b536.png)



Part 2

-The togglable bar containing the report name should also contain a view button that should redirect the user to a new page (mentioned in next point) where the report should be loaded.

![image](https://user-images.githubusercontent.com/96309135/162699159-2647c301-ef43-439b-b48d-bdbe0161519b.png)

- We need to create a page where the report should be displayed. The page should contain
  -Menubar
  -Report Name
  -Report Description

![image](https://user-images.githubusercontent.com/96309135/162700114-c90aff16-530c-41da-9968-2fd446fca408.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
