### ISSUE TITLE
Add domain for job opportunity

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1632]
**Describe the task**
Currently, when we are creating job opportunities from the portal, the domains corresponding to job are being saved through the config file. we don't have a functionality to add job domain from the portal. We need a functionality to store job domains in a separate table.

**ToDos:**

- [x] Create a migration for a table named `hr_job_domains` and its should have the following columns
       ``` Id - unsigned big integer```
       ``` slug - text (it will contain `-` separated name for a domain, for example - people-operations)```
       ``` Name - text (it will have titled value for the slug, for example - People Operations)```
- [x] Provide a button to add a new job domain on the `Add opportunity` page. This page can be accessed by clicking on the `opportunities` tab, and then clicking on the `New opportunity` button. The `Add domain` button can have same UI as the `New Opportunity` button
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/175970743-b6514de3-4bd5-4686-99da-30acac628762.png">

- [x] Clicking on this button, a popup should appear, having a form with the `Domain Name` as a form field
- [x] Submitting this form, the domain name and its slug form should be saved in the `hr_job_domains table

We will further map these domains to the job opportunities, and they would be addressed in a separate ticket.

**Comment by deepankar-sajwan** [comment]
Hi @rohit123-rawat,

There are few issues with your implementation

When user does not input any input domain name and clicks on save changes button, the error is displayed in background, and modal disappears,. Refer screenshot


![image](https://user-images.githubusercontent.com/96309135/180140599-00f3cf7e-fd60-4885-8876-3faf584cbc95.png)


![image](https://user-images.githubusercontent.com/96309135/180140074-a3dec817-e8e4-48cd-b51c-d8b70adc4c44.png)

Solution: Enable save changes button only when any input is provided for damian name.

 Also single domain is added multiple times. 

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180140979-f736b8ae-69e8-4754-93b2-7f90cb018abc.png)


Solution: If domain name with similar name is added, please dispay message to user as **Domain with similar name already exist**.

**Comment by P4NK4J** [comment]
@deepankar-sajwan Creating a separate ticket for this
