### ISSUE TITLE
Incorrect FTE calculation for project whose billing date starts in between of month

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2690]
### Bug Raised By
@GauravGusain98 

### Background
For ColoredCow Full Time Effort(FTE) of an employee is very important. FTE is used to check the engagement of employees and can also be used to plan teams for projects. 

The expected hours from an employee is 8 hours per day. And therefore the formula of FTE is
 ```
FTE = Sum of hours booked by an employee in all the projects / (Total number of days in month till today  * 8)
 ```
### Describe the bug
The user FTE is shown in the user dashboard (Steps provided in the next section). Ideally, the FTE is calculated for a current month that is from the first day of the month to the end of the month, but in some projects where the billing happens in between the FTE calculation comes incorrect. 

Due to this for some users, the FTE is not getting calculated correctly.

### How to open the user dashboard
To see the user's FTE, one can click on the image of his in the project list or can open the Working Staff option from the HR dropdown menu as shown below

<img width="400" alt="image" src="https://user-images.githubusercontent.com/54376313/206443793-21b7f15b-191b-4e28-ae0a-0865c49fb6e8.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54376313/206443691-86a97729-333e-4139-99de-ebc694c99b1a.png">

### To Reproduce
1. Run project module seeder. This will create a new client and project in portal. Check [here](https://nwidart.com/laravel-modules/v6/advanced-tools/artisan-commands#moduleseed) how to run seeder for a specific module
3. Go to the newly created client 
4. Edit the client and fill details of the client
5. In the financial details choose the billing period `monthly` and billing data to `1`
6. Go to the newly created project of that client
7. Check the team member's booked hours. They must have some hours booked for the month
8. Now Go to the user dashboard of that team member 
9. See his FTE. The FTE should come correct.
10. Now again edit client details and set the billing date to the current date 
11. Again see the FTE in the user dashboard the FTE is changed now. This should not happen

### Expected behavior
- [x] The FTE calculation in the user dashboard should not depend on the project billing date. 

### Environment details where the bug is occurring
 - OS: Ubuntu, Mac, Window
 - Environment - Production, Staging, Local

### Additional context
- You need to create a function that calculates the FTE for a user for that month

### Contact person for guidance
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items
- [ ] Find the code that is showing FTE of a team member in the Team member details page
- [ ] Find the logic that is calculation the FTE of  a team member
- [ ] Understand the logic
- [ ] Dry run the logic for the case where the project billing date lies in between the month and find where the FTE data is getting incorrect in the logic
- [ ] Come up with the correct approach to fix the issue for this case
- [ ] Review the approach with the assigned mentor for the task
- [ ] After approval of the approach, implement the approach

**Comment by rahulpanwar16** [comment]
Controllers are used to handle the request logic within the single class. It is a central unit of MVC architecture which fetch the data from model and send it to the view to display it in html .

**Comment by rahulpanwar16** [comment]
Models are used to connect laravel with database and it maps the database table with class name.

**Comment by rahulpanwar16** [comment]
Views are used to display the contents of the website in a form of html tags.
