### ISSUE TITLE
Monthly FTE Report For User

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2775]
**Enhancement suggested by**
@GauravGusain98 

**Is your feature request related to a problem? Please describe.**
For ColoredCow Full Time Effort(FTE) of an employee is very important. FTE is used to check the engagement of employees and can also be used to plan teams for projects. The expected hours from an employee is 8 hours per day.

Currently, we only show the current month's FTE to the user on the user dashboard page as shown below but we also want to give capability to users to see their FTE for previous months
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/213453751-a0b3e128-ac20-4db9-86a7-010cddc61ae4.png">

### How to open the user dashboard
To see the user's FTE, one can click on the image of his in the project list or can open the Working Staff option from the HR dropdown menu as shown below

<img width="400" alt="image" src="https://user-images.githubusercontent.com/54376313/206443793-21b7f15b-191b-4e28-ae0a-0865c49fb6e8.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54376313/206443691-86a97729-333e-4139-99de-ebc694c99b1a.png">

**Additional context**
Once this is implemented, an employee will be able to see his FTE trend which will help him to be more consistent in filling effortsheet and he will be able to see his progress. 

**Point of contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items
**Basics - 1 pointer (Skip if you've already done these in your previous tasks)**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Working with Chart Js - 2 pointer **
- [ ] In the user dashboard page, align the `FTE` and `AMC FTE` in a single line
    <img width="907" alt="image" src="https://user-images.githubusercontent.com/54376313/213455736-d0ef12fd-6b11-4651-9449-06bc700b1935.png">
- [ ] Read about [ChartJs](https://www.chartjs.org/docs/3.6.2/) 
- [ ] Understand how the chart in the invoice Report is working. Share your understanding in comments and discuss it with. @GauravGusain98 _Note: The data comes by making API call from JS to an API route_ 
    <img width="1325" alt="image" src="https://user-images.githubusercontent.com/54376313/213456721-6a751bbc-47bb-4fea-8442-b40b0088f64b.png">
- [ ] Replicate the same chart in the user dashboard below the `FTE` and `AMC FTE` line

**Comment by rahulpanwar16** [comment]
Models are used to connect laravel with database and it maps the database table with class name.

**Comment by rahulpanwar16** [comment]
Views are used to display the contents of the website to the user in a form of html tags. Blade is the engine of the views file which has its own syntax in a simplified way.

**Comment by rahulpanwar16** [comment]
Routes are actually the web URLs that you can visit in your web application and also allows you to route all your application requests to their appropriate controller.

**Comment by rahulpanwar16** [comment]
Controllers are used to handle the request logic within the single class. It is a central unit of MVC architecture which fetch the data from model and send it to the view to display it in html .

**Comment by rahulpanwar16** [comment]
Services contains a specific piece of code\functionality. Main purpose of services is to separate complex and repeated code from controller and made controller more readable, maintainable, easy to test as well as easier to reuse the service.

**Comment by rahulpanwar16** [comment]
1. dd() -> Full form is dump and die and can be defined as a helper function, which is used to dump a variable's contents to the browser and prevent the further program execution.
2. dump() -> dumps all the information about the variable or object on the page, but it does not stop the execution of the program further.

**Comment by rahulpanwar16** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/106467597/215678673-8b258314-bbec-4e16-9879-d4348aa3adce.png)
Above screenshot refers to the dd() and printing hello world.

**Comment by rahulpanwar16** [comment]
For Example-> CSS file : main.css , JS file : script.js , html file : index.html 
Here, main.css is at <link rel="stylesheet" href="main.css">inside the head tag and script.js is at <script src="script.js"></script> inside the body tag of the index.html.

**Comment by rahulpanwar16** [comment]
JS file -> I have taken the reference from the effortTracking Module in view show.blade file. Here, is the canvas tag which contains effortTrackingGraph id and there is a app.js file present which has effortTrackingGraph(). It has the variables defined which is shown in the bar chart and the values are fetch from the effortTrackingController to effortTrackingService where the logic present. 
CSS file -> In the app.js there is a effortTrackingGraph() where datasetValue has borderColor, backgroundColor, type - bar .

**Comment by GauravGusain98** [comment]
> effortTrackingController

Here can you also check how we are getting the values from the controller to frontend as we in normal way we use to make a URl hit but in this case we are not giving any URL in browser manually. Read about making API calls.

Also read more about chart js and see how we are using the data that we are receiving in the chartJS function present in app.js file

**Comment by rahulpanwar16** [comment]
Here, is the output of the report data for 18 months : 
![Screenshot (16)](https://user-images.githubusercontent.com/106467597/224469115-4486784d-5ddc-4ef2-b2a8-d72930340dcf.png)
