### ISSUE TITLE
Change time of effort syncing cron to every hour at 25th minute

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2805]
### Enhancement suggested by
@GauravGusain98 

### Problem that your solution is solving
In ColoredCow we use effort sheet where we track the hour we spent on a particular task. This helps us to calculate our productivity and is also used for billing the client. 

We periodically migrate/update the data present in the effort sheet to the portal. For this, we use a Laravel command that refreshes the booked hours of team members from the effort sheet. This command runs every 4 hours i.e 4 am, 8 am, 12 pm .... 8 pm, 12 am

We also send the details of projects as show below at 10:30 PM on Google chat channel. So that the team member should be aware of their team progress.
![Image](https://user-images.githubusercontent.com/54376313/216901654-21b4380a-1b46-4595-8589-53be8e21ae45.png) 

As the cron refreshes at 4-hour interval therefore if a user has updated the effort after 8 PM then his updated data is not sent on the google channel message.

We need to update the effort data every hour at 25th minute so that the chance of non updated data to be sent on the channel can be minimized. 

### Contact person for help
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items

**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Task Scheduling**
- [ ] Read about [task scheduling](https://laravel.com/docs/8.x/scheduling) in Laravel
- [ ] Update time of task to every hour at 25th minute. Currenlty it is set to every 4 hour
- [ ] Create PR and assign it for review
