### ISSUE TITLE
Show User FTE on dashboard

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2819]
**Enhancement suggested By**
@GauravGusain98 

### Background
For ColoredCow Full Time Effort(FTE) of an employee is very important. FTE is used to check the engagement of employees and can also be used to plan teams for projects. 

The expected hours from an employee is 8 hours per day. And therefore the formula of FTE is
 ```
FTE = Sum of hours booked by an employee in all the projects / (Total number of days in month till today  * 8)
```

### How to see FTE
To see the user's FTE, one can click on the image of his in the project list 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54376313/206443793-21b7f15b-191b-4e28-ae0a-0865c49fb6e8.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/54376313/218672438-d5e3e8ba-aa76-4a9d-b62c-881dab3638ad.png">

**Task Details**
You need to show the current FTE of an employee on the home page. 

### Contact person for guidance
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Actions Items

**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Show FTE**
- [ ] Check how we are getting FTE in the employee details page
- [ ] Figure out how we will show the FTE on dashboard
- [ ] If FTE is less than 1 then show it in red color else green

**Comment by Priyanka-Kaintura** [comment]
Views is the location for keeping all the HTML for the project. It separates the controller logic from presentation logic.

Mostly written using blade templating.

**Comment by Priyanka-Kaintura** [comment]
Routes are defined in routes folder in the project directory. 

The routes/web.php keeps the routes for the web interface. This may also assign routes for the controller and middlewares. 
Redirecting is also possible using redirect function.

**Comment by Priyanka-Kaintura** [comment]
Models are made to interact with the tables in the database. These are used to insert, update, delete, retrieve data from the tables. Models directory : app/Models/

General relationship between model and table is singular ad plural.                                                                                              
eg. : if table is employees then the model will be named as employee.                                                                                             Models extend the  Illuminate\Database\Eloquent\Model class.
