### ISSUE TITLE
Show Project Velocity in dashboard

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2823]
### Background
In ColoredCow some of the projects are charged hourly. So we have to capture the hours booked in the hour and based on it we generate the client invoice/bill for the period. 

The velocity of the project is the ratio of hours booked in the project and the total expected hours in the project for a billing period. In an ideal scenario, it should be 1. 

### Task 
We currently show the velocity of a project on the project listing page 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/54376313/219282099-ce655322-859b-436b-b2f1-80e46bd0feb5.png">

As we also show the user project on the dashboard, so we want to show the project velocity on the project card shown in the dashboard
<img width="992" alt="image" src="https://user-images.githubusercontent.com/54376313/219282286-baee0712-042f-415e-a45f-8ef9de41c83f.png">

**Comment by GauravGusain98** [comment]
### Action Items
**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Velocity**
- [ ] Check how we can get the velocity of a project. See how we are getting it in the project listing page
- [ ] Similarly, show the velocity on dashboard project card on the right hand side of the card

**Comment by kajal7575** [comment]
Good afternoon Sir
 I'm working on the  task that you assign.
I will submit it as soon as possible..

**Comment by jaskaransingh304** [comment]
**Breakdown-**

**Code review and documentation: 0.5-1 hour.**
**Understanding the functionality: 1-2 hours.**
**Making the required changes: 2-3 hours.**
**Testing, code, review, and documentation: 1 hour.**

**Expected Time =6-8 hours.**

**Comment by kajal7575** [comment]
I had bathed my head but it didn't happen.

**Comment by jaskaransingh304** [comment]
@kajal7575 , you can check this,  I have mentioned about the approach  PR-  https://github.com/ColoredCow/portal/pull/3130

**Comment by kajal7575** [comment]
Thanks, I'll check it out.
