### ISSUE TITLE
Add sort functionality in codetrek candidates page

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3195]
**Task Description**
In the Codetrek module, the candidate list is currently sorted by name which sometimes create issues when we add a new candidate and he/she gets added to the list at some random position based on alphabetical order.

Therefore we want a sort by functionality in the CodeTrek module for sorting the list of candidates based on different parameters.

**Expected Behavior**
- [ ] The CodeTrek page should have a sort by button 
- [ ] The sorting can be done based on 
    - [ ] Candidate Name in ascending order such that the list shown in alphabetical order 
    - [ ] Candidate start date in descending order such that the newest candidate should be shown at the top of list.
- [ ] By default the sorting should be done by start date in descending.

**Comment by ImRishabhRawat** [comment]
**Expected Time**

- [ ] System and Process Understanding. `1-2 Hour`
- [ ] Create a dropdown menu "Order BY" to toggle between name and date. `0-1 Hour`
- [ ] Create a route for toggle . `1-2 Hour`
- [ ] Create a function in CodetrekController for sorting. `2-3 Hour`
- [ ] Display the changes in blade file. `2-3 Hour`

**Total Time : 10-11 Hours**
