### ISSUE TITLE
Invoice settlement issue

### ISSUE THREAD

**Issue by AnirudhAP2k** [ColoredCow/portal#3408]
**Is your feature request related to a problem? Please describe.**

* **Current Scenario:**
  *  ColoredCow may have multiple projects for the same client.
  *  Invoices are generated for each project. 
  *  Client payments may be made either in a total sum for all invoices or for just a few.

* **Problems:**
 1. **Manual Calculation Burden:**
    * The finance team faces the challenge of calculating the amount received for each invoice when clients pay in partial sums or total sums, adding to their workload.
     * This manual calculation process is time-consuming and prone to errors.

2. **Incomplete Payment Notification:**
    * Email notifications are sent to confirm the settlement of project payments, but they do not address any remaining unpaid invoices for the same client that have passed their due date.
    * This lack of notification for leftover invoices may lead to delays in payments or the finance team might fail to notice past-due invoices.

**Describe the solution you'd like**

  * All the projects from the same client will be grouped together by using the client filter.
 * To gain more information, all the invoices will be listed along with necessary details, such as invoice number, project cost, GST amount.
 * These invoices will be sorted based on the due date (oldest to newest).
 * Based on the information, a net payable amount(NPA, a sum to be paid to settle an invoice) will be displayed for each invoice.
 * There will be input fields for amount paid and comments.
 * The user can input the bank statement in the comment, and so the total amount (sum paid by the client for multiple invoices) will be fetched to the amount paid.
 * Next, the invoices which will add up to the amount sent by the client will be found.

**Approaches to determine settled invoices :-**

* Preferred approach:-

  * Assumptions:

    *   Taxes on the invoices are already known beforehand and is the same for each invoice.
    *   Information of the invoices for which the client has made the payment is not known.

  * Process:

    * The system will compute the net payable amount for each invoice.
    *  The user will then fill the grand total amount in an input field, or paste the bank statement in the comment section.
    *  Now, the system will filter the invoices which can be settled using the grand total amount.
    *  The invoices which are settled will be displayed to the user.

   * Further process(will be done after either approaches):
      * After the invoices are settled by the system, a confirmation email will be sent to the client giving the information of the invoices which were settled.
      * Additionally, an email will be sent to the finance head giving the information about the unsettled invoices of a particular client.

* Edge Cases:-
  *  In case if two invoices are of the same amount, it may lead to confusion, as it won’t be clear which invoice the client intended to settle. To avoid this issue, further communication with the client may be required.
  * In case TDS deducted for two invoices is not the same, determining the net payable amount for each invoice becomes challenging. To solve the issue, it is essential to communicate with the client and obtain information about the TDS for each invoice.

* Issue of determining TDS percentage:-
  * Knowing the TDS beforehand can be challenging because clients don’t generally mention how much TDS was deducted before making the payment. Right now we have to go with assumptions on how much TDS is getting deducted.
  *  We can solve this issue in the following ways:
       *   We can specify the TDS percentage in the invoice, so that the client is aware of how much TDS they should deduct.
       * We should ensure that the client agrees to communicate the deducted TDS amount when making the payment.

**Additional context**

***There is no space to show pending invoices of the same client***
![Screenshot 2024-01-30 154515](https://github.com/ColoredCow/portal/assets/128780218/807720d9-0153-4914-8423-05b4f92b65e0)

**Comment by AnirudhAP2k** [comment]
**Sub-tasks**

- [ ] Group the invoices of same client together.
- [ ] Display the list of client having active projects as a landing page for, ***Finance -> Invoices***.
- [ ] Add necessary details of the clients like Unsettled invoices, total amount etc. alongside client names in form of a table.
- [ ] Add filters for Year, Month, Status and Client, to filter out the data in the table.
- [ ] Once user navigates to a client for more information, show all of the invoices along with the details like Invoice Number, due date, sent on date, status etc.
- [ ] Provide a dropdown for status, i.e, sent (default value), paid and disputed.
- [ ] If the status is marked paid, a calculator will be shown, which will work on either of the approach, as defined in the issue.
