### ISSUE TITLE
Ability to mark book as mandatory for all the employees of coloredcow

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#715]
We already have a category section for books. Let's use that to mark the books as mandatory for all users. 

- [ ] 1. Let's add a new column in the book_category table with the name slug. This will work like a string Identifier for all the categories. i.e if the book category is **Business & Economics** the value of slug will be **business_economics**.  (https://github.com/ColoredCow/portal/issues/2932)

- [ ] 2. Write a seeder to add the following category in the books category table(if not exists) (https://github.com/ColoredCow/portal/issues/2933)
            a. mandatory-for-all
            b. mandatory-for-design
            c. mandatory-for-tech

- [ ] 3. We will show the prompt for a user if he hasn't read all the mandatory books. (https://github.com/ColoredCow/portal/issues/2934)
