### ISSUE TITLE
Search & Filter in job application listing

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#806]
**Describe the task**
Work on the new search & filter functionality as designed:
1. Prototype link: https://www.figma.com/proto/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?page-id=2%3A2&node-id=194%3A2520&viewport=-1124%2C469%2C0.3099302053451538&scaling=min-zoom
2. Design link: https://www.figma.com/file/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?node-id=2%3A2

**Expected behavior**
- [x] Create a VueJS component for tags input that opens up when you click on the input field.
- [x] Work on only the status field. Other search parameters to be worked on later.

**References**
Check out ColoredCow/old-portal#163 for more details

**Comment by atul5238** [comment]
**Subtasks**
- [ ] Modal with multiselect input type.

**Comment by srivastava-jyoti** [comment]
Closing
